-- SHIP Tables for PostgreSQL (Sevkiyat/İrsaliye)

-- SHIP Table (Sevkiyat ana tablo)
CREATE TABLE IF NOT EXISTS ship (
    ship_id SERIAL PRIMARY KEY,
    wrk_id VARCHAR(43),
    purchase_sales BOOLEAN,
    serial_number VARCHAR(50),
    ship_number VARCHAR(50),
    ship_type INTEGER,
    ship_method INTEGER,
    ship_date TIMESTAMP,
    ship_status INTEGER DEFAULT 1,
    ship_address_id INTEGER,
    is_with_ship BOOLEAN,
    company_id INTEGER,
    partner_id INTEGER,
    consumer_id INTEGER,
    employee_id INTEGER,
    deliver_date TIMESTAMP,
    location INTEGER,
    deliver_store_id INTEGER,
    deliver_emp VARCHAR(50),
    department_in INTEGER,
    location_in INTEGER,
    other_money VARCHAR(43),
    other_money_value NUMERIC(18,6),
    discounttotal NUMERIC(18,6),
    grosstotal NUMERIC(18,6),
    nettotal NUMERIC(18,6),
    taxtotal NUMERIC(18,6),
    otv_total NUMERIC(18,6),
    address VARCHAR(500),
    paymethod_id INTEGER,
    order_id INTEGER,
    project_id INTEGER,
    process_cat INTEGER,
    dispatch_ship_id INTEGER,
    is_exported BOOLEAN,
    is_delivered BOOLEAN,
    city_id INTEGER,
    county_id INTEGER,
    due_date TIMESTAMP,
    sa_discount NUMERIC(18,6),
    ref_no VARCHAR(2000),
    general_prom_id INTEGER,
    general_prom_limit INTEGER,
    general_prom_amount NUMERIC(18,6),
    general_prom_discount NUMERIC(18,6),
    free_prom_id INTEGER,
    free_prom_limit INTEGER,
    free_prom_cost NUMERIC(18,6),
    free_prom_amount INTEGER,
    free_prom_stock_id INTEGER,
    free_stock_price NUMERIC(18,6),
    free_stock_money VARCHAR(43),
    prod_order_number INTEGER,
    prod_order_result_number INTEGER,
    card_paymethod_id INTEGER,
    card_paymethod_rate NUMERIC(18,6),
    ship_detail TEXT,
    sale_emp INTEGER,
    is_ship_iptal BOOLEAN DEFAULT false,
    deliver_emp_id INTEGER,
    commethod_id INTEGER,
    deliver_par_id INTEGER,
    is_dispatch BOOLEAN DEFAULT false,
    work_id INTEGER,
    deliver_comp_id INTEGER,
    deliver_cons_id INTEGER,
    subscription_id INTEGER,
    project_id_in INTEGER,
    cargo_status BOOLEAN,
    record_emp INTEGER,
    record_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_emp INTEGER,
    update_date TIMESTAMP,
    metal_order_id INTEGER,
    is_send_webservice BOOLEAN,
    is_from_return BOOLEAN,
    service_id INTEGER,
    is_received_webservice BOOLEAN,
    process_stage INTEGER,
    print_count INTEGER,
    print_date TIMESTAMP,
    action_date TIMESTAMP,
    country_id INTEGER,
    CONSTRAINT fk_ship_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE SET NULL,
    CONSTRAINT fk_ship_paymethod FOREIGN KEY (paymethod_id) REFERENCES setup_paymethod(paymethod_id) ON DELETE SET NULL
);

-- SHIP_ROW Table (Sevkiyat satırları)
CREATE TABLE IF NOT EXISTS ship_row (
    ship_row_id SERIAL PRIMARY KEY,
    ship_id INTEGER,
    purchase_sales BOOLEAN,
    ship_status INTEGER DEFAULT 1,
    product_id INTEGER,
    price NUMERIC(18,6),
    price_other NUMERIC(18,6),
    amount NUMERIC(18,6),
    unit VARCHAR(43),
    unit_id INTEGER,
    tax NUMERIC(10,2),
    paymethod_id INTEGER,
    order_row INTEGER,
    catalog_id INTEGER,
    stock_id INTEGER,
    name_product VARCHAR(500),
    ship_date TIMESTAMP,
    spect_var_id INTEGER,
    spect_var_name VARCHAR(500),
    cost_id INTEGER,
    cost_price NUMERIC(18,6),
    margin NUMERIC(10,2),
    extra_cost NUMERIC(18,6),
    discount NUMERIC(10,2) DEFAULT 0,
    discount2 NUMERIC(10,2) DEFAULT 0,
    discount3 NUMERIC(10,2) DEFAULT 0,
    discount4 NUMERIC(10,2) DEFAULT 0,
    discount5 NUMERIC(10,2) DEFAULT 0,
    discount6 NUMERIC(10,2) DEFAULT 0,
    discount7 NUMERIC(10,2) DEFAULT 0,
    discount8 NUMERIC(10,2) DEFAULT 0,
    discount9 NUMERIC(10,2) DEFAULT 0,
    discount10 NUMERIC(10,2) DEFAULT 0,
    discounttotal NUMERIC(18,6),
    grosstotal NUMERIC(18,6),
    nettotal NUMERIC(18,6),
    taxtotal NUMERIC(18,6),
    deliver_date TIMESTAMP,
    deliver_dept INTEGER,
    deliver_loc INTEGER,
    other_money VARCHAR(43),
    other_money_value NUMERIC(18,6),
    other_money_gross_total NUMERIC(18,6),
    lot_no VARCHAR(100),
    darali NUMERIC(18,6),
    dara NUMERIC(18,6),
    row_order_id INTEGER,
    prom_comission NUMERIC(18,6),
    prom_cost NUMERIC(18,6),
    discount_cost NUMERIC(18,6),
    is_promotion BOOLEAN,
    prom_id INTEGER,
    prom_stock_id INTEGER,
    import_invoice_id INTEGER,
    import_period_id INTEGER,
    is_commission BOOLEAN DEFAULT false,
    unique_relation_id VARCHAR(100),
    product_name2 VARCHAR(600),
    amount2 NUMERIC(18,6),
    unit2 VARCHAR(50),
    extra_price NUMERIC(18,6),
    shelf_number INTEGER,
    product_manufact_code VARCHAR(100),
    extra_price_total NUMERIC(18,6),
    otv_oran NUMERIC(10,2),
    otvtotal NUMERIC(18,6),
    basket_extra_info_id INTEGER,
    select_info_extra INTEGER,
    detail_info_extra VARCHAR(500),
    prom_relation_id VARCHAR(100),
    related_ship_id INTEGER,
    related_ship_period INTEGER,
    basket_employee_id INTEGER,
    list_price NUMERIC(18,6),
    number_of_installment INTEGER,
    due_date INTEGER,
    extra_price_other_total NUMERIC(18,6),
    price_cat INTEGER,
    karma_product_id INTEGER,
    service_id INTEGER,
    ek_tutar_price NUMERIC(18,6),
    row_internaldemand_id INTEGER,
    wrk_row_id VARCHAR(40),
    wrk_row_relation_id VARCHAR(40),
    related_action_id INTEGER,
    related_action_table VARCHAR(43),
    depth_value NUMERIC(18,6),
    width_value NUMERIC(18,6),
    height_value NUMERIC(18,6),
    row_project_id INTEGER,
    to_shelf_number INTEGER,
    row_paymethod_id INTEGER,
    row_work_id INTEGER,
    expense_center_id INTEGER,
    expense_item_id INTEGER,
    activity_type_id INTEGER,
    acc_code VARCHAR(100),
    subscription_id INTEGER,
    assetp_id INTEGER,
    bsmv_rate NUMERIC(10,2),
    bsmv_amount NUMERIC(18,6),
    bsmv_currency NUMERIC(18,6),
    oiv_rate NUMERIC(10,2),
    oiv_amount NUMERIC(18,6),
    tevkifat_rate NUMERIC(10,2),
    tevkifat_amount NUMERIC(18,6),
    reason_code INTEGER,
    reason_name VARCHAR(250),
    gtip_number VARCHAR(100),
    weight NUMERIC(18,6),
    specific_weight NUMERIC(18,6),
    volume NUMERIC(18,6),
    CONSTRAINT fk_ship_row_ship FOREIGN KEY (ship_id) REFERENCES ship(ship_id) ON DELETE CASCADE,
    CONSTRAINT fk_ship_row_product FOREIGN KEY (product_id) REFERENCES product(product_id) ON DELETE SET NULL,
    CONSTRAINT fk_ship_row_stock FOREIGN KEY (stock_id) REFERENCES stocks(stock_id) ON DELETE SET NULL
);

-- SHIP_MONEY Table (Sevkiyat para birimi)
CREATE TABLE IF NOT EXISTS ship_money (
    action_money_id SERIAL PRIMARY KEY,
    money_type VARCHAR(43),
    action_id INTEGER,
    rate2 NUMERIC(18,6),
    rate1 NUMERIC(18,6),
    is_selected BOOLEAN,
    CONSTRAINT fk_ship_money_action FOREIGN KEY (action_id) REFERENCES ship(ship_id) ON DELETE CASCADE
);

-- İndeksler
CREATE INDEX idx_ship_number ON ship(ship_number);
CREATE INDEX idx_ship_date ON ship(ship_date);
CREATE INDEX idx_ship_company ON ship(company_id);
CREATE INDEX idx_ship_status ON ship(ship_status);
CREATE INDEX idx_ship_type ON ship(ship_type);
CREATE INDEX idx_ship_method ON ship(ship_method);
CREATE INDEX idx_ship_row_ship ON ship_row(ship_id);
CREATE INDEX idx_ship_row_product ON ship_row(product_id);
CREATE INDEX idx_ship_row_stock ON ship_row(stock_id);
CREATE INDEX idx_ship_money_action ON ship_money(action_id);

-- Yorum satırları
COMMENT ON TABLE ship IS 'Sevkiyat/İrsaliye ana tablo';
COMMENT ON TABLE ship_row IS 'Sevkiyat satır detayları';
COMMENT ON TABLE ship_money IS 'Sevkiyat para birimi kurları';
COMMENT ON COLUMN ship.purchase_sales IS 'Alış/Satış (true:Satış, false:Alış)';
COMMENT ON COLUMN ship.ship_number IS 'İrsaliye numarası';
COMMENT ON COLUMN ship.ship_type IS 'İrsaliye tipi';
COMMENT ON COLUMN ship.ship_status IS 'İrsaliye durumu (1:Aktif, 0:İptal)';
COMMENT ON COLUMN ship.is_ship_iptal IS 'İptal edildi mi?';
COMMENT ON COLUMN ship.is_dispatch IS 'Sevk edildi mi?';
COMMENT ON COLUMN ship_row.discount IS 'İskonto 1 (%)';
COMMENT ON COLUMN ship_row.discount2 IS 'İskonto 2 (%)';
