CREATE TABLE IF NOT EXISTS productcategory_workstationgroup_relation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_catid INTEGER NOT NULL,
    workstation_id INTEGER NOT NULL,
    record_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pcwgr_product_cat
        FOREIGN KEY (product_catid) REFERENCES product_cat(product_catid) ON DELETE CASCADE,
    CONSTRAINT fk_pcwgr_workstation
        FOREIGN KEY (workstation_id) REFERENCES workstations(station_id) ON DELETE CASCADE,
    CONSTRAINT uix_pcwgr_product_cat_workstation UNIQUE (product_catid, workstation_id)
);

CREATE INDEX IF NOT EXISTS idx_pcwgr_product_catid
    ON productcategory_workstationgroup_relation(product_catid);

CREATE INDEX IF NOT EXISTS idx_pcwgr_workstation_id
    ON productcategory_workstationgroup_relation(workstation_id);
