-- Product and Stock Management Tables for PostgreSQL

-- STOCKS Table
CREATE TABLE IF NOT EXISTS STOCKS(
	STOCK_ID SERIAL PRIMARY KEY,
	STOCK_CODE VARCHAR(150) NOT NULL,
	STOCK_CODE_2 VARCHAR(150),
	PRODUCT_ID INTEGER NOT NULL,
	PROPERTY VARCHAR(500),
	BARCOD VARCHAR(50),
	PRODUCT_UNIT_ID INTEGER,
	MANUFACT_CODE VARCHAR(100),
	STOCK_STATUS BOOLEAN,
	RECORD_EMP INTEGER,
	RECORD_IP VARCHAR(50),
	RECORD_DATE TIMESTAMP,
	UPDATE_EMP INTEGER,
	UPDATE_IP VARCHAR(50),
	UPDATE_DATE TIMESTAMP,
	SERIAL_BARCOD DOUBLE PRECISION,
	IS_MAIN_STOCK BOOLEAN
);

-- STOCKS_ROW Table
CREATE TABLE IF NOT EXISTS STOCKS_ROW(
	STOCKS_ROW_ID SERIAL PRIMARY KEY,
	STOCK_ID INTEGER,
	PRODUCT_ID INTEGER,
	UPD_ID INTEGER,
	PROCESS_TYPE INTEGER,
	STOCK_IN DOUBLE PRECISION DEFAULT 0,
	STOCK_OUT DOUBLE PRECISION DEFAULT 0,
	STORE INTEGER,
	STORE_LOCATION INTEGER,
	PROCESS_DATE TIMESTAMP,
	SPECT_VAR_ID INTEGER,
	IS_ONCONSIGNMENT BOOLEAN,
	LOT_NO VARCHAR(100),
	SHELF_NUMBER INTEGER,
	PRODUCT_MANUFACT_CODE VARCHAR(100),
	DELIVER_DATE TIMESTAMP,
	AMOUNT2 DOUBLE PRECISION,
	UNIT2 VARCHAR(50),
	ROW_ID INTEGER,
	WRK_ROW_ID VARCHAR(50),
	DEPTH_VALUE DOUBLE PRECISION,
	WIDTH_VALUE DOUBLE PRECISION,
	HEIGHT_VALUE DOUBLE PRECISION,
	PROCESS_TIME TIMESTAMP
);

-- STOCK_FIS Table
CREATE TABLE IF NOT EXISTS STOCK_FIS(
	FIS_ID SERIAL PRIMARY KEY,
	FIS_TYPE INTEGER,
	FIS_NUMBER VARCHAR(50),
	LOCATION_OUT INTEGER,
	DEPARTMENT_OUT INTEGER,
	LOCATION_IN INTEGER,
	DEPARTMENT_IN INTEGER,
	EMPLOYEE_ID INTEGER,
	FIS_DATE TIMESTAMP,
	DELIVER_DATE TIMESTAMP,
	PROD_ORDER_NUMBER INTEGER,
	PROD_ORDER_RESULT_NUMBER INTEGER,
	PROCESS_CAT INTEGER,
	REF_NO VARCHAR(2000),
	IS_PRODUCTION BOOLEAN DEFAULT FALSE,
	FIS_DETAIL TEXT,
	SUBSCRIPTION_ID INTEGER,
	IS_STOCK_TRANSFER INTEGER,
	RECORD_DATE TIMESTAMP,
	RECORD_EMP INTEGER,
	RECORD_IP VARCHAR(50),
	UPDATE_DATE TIMESTAMP,
	UPDATE_EMP INTEGER,
	UPDATE_IP VARCHAR(50)
);

-- STOCK_FIS_ROW Table
CREATE TABLE IF NOT EXISTS STOCK_FIS_ROW(
	STOCK_FIS_ROW_ID SERIAL PRIMARY KEY,
	FIS_ID INTEGER,
	FIS_NUMBER VARCHAR(50),
	TOTAL DOUBLE PRECISION,
	TOTAL_TAX DOUBLE PRECISION,
	NET_TOTAL DOUBLE PRECISION,
	STOCK_ID INTEGER,
	AMOUNT DOUBLE PRECISION,
	UNIT VARCHAR(43),
	UNIT_ID INTEGER,
	LOT_NO VARCHAR(100),
	UNIQUE_RELATION_ID VARCHAR(100),
	PRODUCT_NAME2 VARCHAR(500),
	AMOUNT2 DOUBLE PRECISION,
	UNIT2 VARCHAR(50),
	SHELF_NUMBER INTEGER,
	PRODUCT_MANUFACT_CODE VARCHAR(100),
	WRK_ROW_ID VARCHAR(40),
	WRK_ROW_RELATION_ID VARCHAR(40),
	TO_SHELF_NUMBER INTEGER,
	PBS_ID INTEGER,
	BASKET_EXTRA_INFO_ID INTEGER,
	SELECT_INFO_EXTRA INTEGER,
	DETAIL_INFO_EXTRA VARCHAR(500)
);

-- PRODUCT_UNIT Table
CREATE TABLE IF NOT EXISTS PRODUCT_UNIT(
	PRODUCT_UNIT_ID SERIAL PRIMARY KEY,
	PRODUCT_UNIT_STATUS BOOLEAN NOT NULL DEFAULT TRUE,
	PRODUCT_ID INTEGER NOT NULL,
	MAIN_UNIT_ID INTEGER,
	MAIN_UNIT VARCHAR(50),
	UNIT_ID INTEGER,
	ADD_UNIT VARCHAR(50),
	MULTIPLIER DOUBLE PRECISION DEFAULT 1,
	DIMENTION VARCHAR(50),
	DESI_VALUE DOUBLE PRECISION,
	WEIGHT DECIMAL(38, 8),
	IS_MAIN BOOLEAN DEFAULT FALSE,
	IS_SHIP_UNIT BOOLEAN DEFAULT FALSE,
	UNIT_MULTIPLIER DOUBLE PRECISION,
	UNIT_MULTIPLIER_STATIC INTEGER,
	VOLUME DOUBLE PRECISION,
	RECORD_DATE TIMESTAMP,
	RECORD_EMP INTEGER,
	UPDATE_DATE TIMESTAMP,
	UPDATE_EMP INTEGER,
	IS_ADD_UNIT BOOLEAN,
	UNIT2 VARCHAR(50),
	QUANTITY DOUBLE PRECISION DEFAULT 1,
	PACKAGES INTEGER,
	PATH VARCHAR(500),
	PACKAGE_CONTROL_TYPE INTEGER,
	INSTRUCTION VARCHAR(200)
);

-- PRODUCT_BRANDS Table
CREATE TABLE IF NOT EXISTS PRODUCT_BRANDS(
	BRAND_ID SERIAL PRIMARY KEY,
	BRAND_NAME TEXT,
	BRAND_CODE VARCHAR(50),
	DETAIL VARCHAR(1000),
	IS_ACTIVE BOOLEAN,
	IS_INTERNET BOOLEAN,
	RECORD_EMP INTEGER,
	RECORD_DATE TIMESTAMP,
	RECORD_IP VARCHAR(50),
	UPDATE_EMP INTEGER,
	UPDATE_DATE TIMESTAMP,
	UPDATE_IP VARCHAR(50)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_stocks_product_id ON STOCKS(PRODUCT_ID);
CREATE INDEX IF NOT EXISTS idx_stocks_row_stock_id ON STOCKS_ROW(STOCK_ID);
CREATE INDEX IF NOT EXISTS idx_stocks_row_product_id ON STOCKS_ROW(PRODUCT_ID);
CREATE INDEX IF NOT EXISTS idx_stock_fis_row_fis_id ON STOCK_FIS_ROW(FIS_ID);
CREATE INDEX IF NOT EXISTS idx_stock_fis_row_stock_id ON STOCK_FIS_ROW(STOCK_ID);
CREATE INDEX IF NOT EXISTS idx_product_unit_product_id ON PRODUCT_UNIT(PRODUCT_ID);

COMMENT ON TABLE STOCKS IS 'Stock master data table';
COMMENT ON TABLE STOCKS_ROW IS 'Stock transaction rows';
COMMENT ON TABLE STOCK_FIS IS 'Stock transaction documents';
COMMENT ON TABLE STOCK_FIS_ROW IS 'Stock transaction document rows';
COMMENT ON TABLE PRODUCT_UNIT IS 'Product unit definitions';
COMMENT ON TABLE PRODUCT_BRANDS IS 'Product brands';
