USE [w3Partner]
GO

/****** Object:  Table [PRODUCT_IMAGES]    Script Date: 24.04.2026 14:28:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCT_IMAGES](
	[PRODUCT_ID] [int] NOT NULL,
	[PRODUCT_IMAGEID] [int] IDENTITY(1,1) NOT NULL,
	[PATH] [nvarchar](100) NULL,
	[DETAIL] [nvarchar](max) NULL,
	[IMAGE_SIZE] [int] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[PROPERTY_ID] [int] NULL,
	[UPDATE_PAR] [int] NULL,
	[IS_INTERNET] [bit] NULL,
	[PATH_SERVER_ID] [int] NULL,
	[STOCK_ID] [nvarchar](100) NULL,
	[IS_EXTERNAL_LINK] [bit] NULL,
	[LANGUAGE_ID] [nvarchar](43) NULL,
	[VIDEO_LINK] [bit] NULL,
	[VIDEO_PATH] [nvarchar](200) NULL,
	[PRD_IMG_NAME] [nvarchar](200) NULL,
	[LIST_NO] [int] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	
 CONSTRAINT [PK_PRODUCT_IMAGES_PRODUCT_IMAGEID] PRIMARY KEY CLUSTERED 
(
	[PRODUCT_IMAGEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


