
GO

/****** Object:  Table [PRODUCT_TREE]    Script Date: 3/25/2026 10:17:50 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCT_TREE](
	[PRODUCT_TREE_ID] [int] IDENTITY(1,1) NOT NULL,
	[RELATED_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[HIERARCHY] [nvarchar](100) NULL,
	[IS_TREE] [bit] NULL,
	[AMOUNT] [float] NULL,
	[UNIT_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[IS_CONFIGURE] [bit] NULL,
	[IS_SEVK] [bit] NULL,
	[SPECT_MAIN_ID] [int] NULL,
	[LINE_NUMBER] [int] NULL,
	[OPERATION_TYPE_ID] [int] NULL,
	[OPERATION_DURATION] [nvarchar](43) NULL,
	[STATION_ID] [int] NULL,
	[IS_PHANTOM] [bit] NULL,
	[QUESTION_ID] [int] NULL,
	[RELATED_PRODUCT_TREE_ID] [int] NULL,
	[PROCESS_STAGE] [int] NULL,
	[MAIN_STOCK_ID] [int] NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[HISTORY_DATE] [datetime] NULL,
	[HISTORY_EMP] [int] NULL,
	[IS_FREE_AMOUNT] [bit] NULL,
	[FIRE_AMOUNT] [float] NULL,
	[FIRE_RATE] [float] NULL,
	[DETAIL] [nvarchar](150) NULL,
	[PRODUCT_PROPERTY] [int] NULL,
	[LAST_PRICE] [float] NULL,
	[SUPPLIER_COMPANY_ID] [int] NULL,
	[ALTERNATIVE_STOCK_ID] [int] NULL,
	[PRODUCT_SAMPLE_ID] [int] NULL,
	[PRODUCT_LENGTH] [int] NULL,
	[TECHNICAL_POINT] [int] NULL,
	[PRODUCT_HEIGHT] [int] NULL,
	[TARGET_PRICE] [float] NULL,
	[TREE_TYPE] [int] NULL,
	[TARGET_PRICE_CURRENCY] [nvarchar](10) NULL,
	[PRODUCTION_CODE] [nvarchar](50) NULL,
	[PRODUCT_WIDTH] [int] NULL,
	[AMOUNT2] [float] NULL,
 CONSTRAINT [PK_PRODUCT_TREE_PRODUCT_TREE_ID] PRIMARY KEY CLUSTERED 
(
	[PRODUCT_TREE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [PRODUCT_TREE] ADD  DEFAULT ((0)) FOR [IS_TREE]
GO

ALTER TABLE [PRODUCT_TREE] ADD  DEFAULT ((0)) FOR [IS_SEVK]
GO

ALTER TABLE [PRODUCT_TREE] ADD  DEFAULT ((0)) FOR [IS_PHANTOM]
GO



GO

/****** Object:  Table [SPECT_MAIN]    Script Date: 3/25/2026 10:18:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SPECT_MAIN](
	[SPECT_MAIN_ID] [int] IDENTITY(1,1) NOT NULL,
	[WRK_ID] [nvarchar](100) NULL,
	[SPECT_MAIN_NAME] [nvarchar](500) NULL,
	[SPECT_TYPE] [int] NULL,
	[DETAIL] [nvarchar](max) NULL,
	[PRODUCT_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[IS_TREE] [bit] NULL,
	[SPECT_STATUS] [bit] NULL,
	[FUSEACTION] [nvarchar](150) NULL,
	[IS_LIMITED_STOCK] [bit] NULL,
	[SPECIAL_CODE_1] [nvarchar](250) NULL,
	[SPECIAL_CODE_2] [nvarchar](250) NULL,
	[SPECIAL_CODE_3] [nvarchar](250) NULL,
	[SPECIAL_CODE_4] [nvarchar](250) NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_PAR] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[RECORD_DATE] [datetime] NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_PAR] [int] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[RECORD_CON] [int] NULL,
	[UPDATE_CON] [int] NULL,
	[IS_MIX_PRODUCT] [bit] NULL,
	[STAGE] [int] NULL,
	[EMPLOYEE_ID] [int] NULL,
	[SAVE_DATE] [datetime] NULL,
 CONSTRAINT [PK_SPECT_MAIN_SPECT_MAIN_ID] PRIMARY KEY CLUSTERED 
(
	[SPECT_MAIN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [SPECT_MAIN] ADD  DEFAULT ((1)) FOR [SPECT_STATUS]
GO

ALTER TABLE [SPECT_MAIN] ADD  DEFAULT ((1)) FOR [IS_LIMITED_STOCK]
GO

ALTER TABLE [SPECT_MAIN] ADD  CONSTRAINT [DF_SPECT_MAIN_IS_MIX_PRODUCT]  DEFAULT ((0)) FOR [IS_MIX_PRODUCT]
GO



GO

/****** Object:  Table [SPECT_MAIN_ROW]    Script Date: 3/25/2026 10:18:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SPECT_MAIN_ROW](
	[SPECT_MAIN_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[SPECT_MAIN_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[AMOUNT] [float] NULL,
	[PROPERTY_ID] [int] NULL,
	[VARIATION_ID] [int] NULL,
	[TOTAL_MIN] [float] NULL,
	[TOTAL_MAX] [float] NULL,
	[PRODUCT_NAME] [nvarchar](500) NULL,
	[IS_PROPERTY] [int] NULL,
	[IS_CONFIGURE] [bit] NULL,
	[IS_SEVK] [bit] NULL,
	[TOTAL_VALUE] [float] NULL,
	[TOLERANCE] [int] NULL,
	[PRODUCT_SPACE] [float] NULL,
	[PRODUCT_DISPLAY] [float] NULL,
	[PRODUCT_RATE] [float] NULL,
	[PRODUCT_LIST_PRICE] [float] NULL,
	[CALCULATE_TYPE] [int] NULL,
	[RELATED_MAIN_SPECT_ID] [int] NULL,
	[RELATED_MAIN_SPECT_NAME] [nvarchar](150) NULL,
	[LINE_NUMBER] [int] NULL,
	[DIMENSION] [float] NULL,
	[CONFIGURATOR_VARIATION_ID] [int] NULL,
	[IS_PHANTOM] [bit] NULL,
	[RELATED_TREE_ID] [int] NULL,
	[OPERATION_TYPE_ID] [int] NULL,
	[QUESTION_ID] [int] NULL,
	[STATION_ID] [int] NULL,
	[IS_FREE_AMOUNT] [bit] NULL,
	[FIRE_AMOUNT] [float] NULL,
	[FIRE_RATE] [float] NULL,
	[DETAIL] [nvarchar](150) NULL,
	[IS_QUALITY_TYPE] [bit] NULL,
	[QUALITY_TYPE_ID] [int] NULL,
	[QUALITY_STANDART_VALUE] [float] NULL,
	[QUALITY_MEASURE] [float] NULL,
	[QUALITY_TOLERANCE] [float] NULL,
 CONSTRAINT [PK_SPECT_MAIN_ROW_SPECT_MAIN_ROW_ID] PRIMARY KEY CLUSTERED 
(
	[SPECT_MAIN_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [SPECT_MAIN_ROW] ADD  DEFAULT ((0)) FOR [IS_PHANTOM]
GO



GO

/****** Object:  Table [SPECTS]    Script Date: 3/25/2026 10:18:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SPECTS](
	[SPECT_VAR_ID] [int] IDENTITY(1,1) NOT NULL,
	[WRK_ID] [nvarchar](100) NULL,
	[PRODUCT_CONFIGURATOR_ID] [int] NULL,
	[SPECT_VAR_NAME] [nvarchar](500) NULL,
	[SPECT_TYPE] [int] NULL,
	[DETAIL] [nvarchar](max) NULL,
	[PRODUCT_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[TOTAL_AMOUNT] [float] NULL,
	[OTHER_MONEY_CURRENCY] [nvarchar](43) NULL,
	[OTHER_TOTAL_AMOUNT] [float] NULL,
	[IS_TREE] [bit] NULL,
	[PRODUCT_AMOUNT] [float] NULL,
	[PRODUCT_AMOUNT_CURRENCY] [nvarchar](43) NULL,
	[SPECT_COST] [float] NULL,
	[SPECT_COST_CURRENCY] [nvarchar](43) NULL,
	[SPECT_MAIN_ID] [int] NULL,
	[FILE_NAME] [nvarchar](50) NULL,
	[FILE_SERVER_ID] [int] NULL,
	[MARJ_TOTAL_AMOUNT] [float] NULL,
	[MARJ_OTHER_TOTAL_AMOUNT] [float] NULL,
	[MARJ_AMOUNT] [float] NULL,
	[MARJ_PERCENT] [float] NULL,
	[IS_LIMITED_STOCK] [bit] NULL,
	[SPECIAL_CODE_1] [nvarchar](250) NULL,
	[SPECIAL_CODE_2] [nvarchar](250) NULL,
	[SPECIAL_CODE_3] [nvarchar](250) NULL,
	[SPECIAL_CODE_4] [nvarchar](250) NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_CONS] [int] NULL,
	[RECORD_PAR] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[RECORD_DATE] [datetime] NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_PAR] [int] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_CONS] [int] NULL,
	[IS_MIX_PRODUCT] [bit] NULL,
	[STAGE] [int] NULL,
	[EMPLOYEE_ID] [int] NULL,
	[SAVE_DATE] [datetime] NULL,
	[DOUBLE_BUTT_ROOT_GAP] [float] NULL,
	[DOUBLE_BUTT_SEAM_GROOVE] [float] NULL,
	[DOUBLE_BUTT_DEPTH_OF_ROOT_FACE] [float] NULL,
	[DOUBLE_BUTT_CAP] [float] NULL,
	[BUTT_ROOT_GAP] [float] NULL,
	[BUTT_STEEL_DENSITY] [float] NULL,
	[SINGLE_BUTT_ALPHA1] [float] NULL,
	[SINGLE_BUTT_ALPHA2] [float] NULL,
	[FILLET_BUTT_CAP] [float] NULL,
	[WELDING_ID] [int] NULL,
	[SINGLE_BUTT_OVERLAP] [float] NULL,
	[BUTT_CAP] [float] NULL,
	[SIZE] [float] NULL,
	[DOUBLE_BUTT_ALPHA_1] [float] NULL,
	[DOUBLE_BUTT_ALPHA_2] [float] NULL,
	[DOUBLE_BUTT_STEEL_DENSITY] [float] NULL,
	[QUALITY_ID] [int] NULL,
	[DOUBLE_BUTT_ALPHA_3] [float] NULL,
	[DOUBLE_BUTT_ALPHA_4] [float] NULL,
	[DIAMETER] [float] NULL,
	[DOUBLE_BUTT_CAP_2] [float] NULL,
	[PRODUCT_CAT] [int] NULL,
	[CAP_UNIT] [float] NULL,
	[BUTT_SHEET_THICKNESS] [float] NULL,
	[SINGLE_BUTT_SHEET_THICKNESS] [float] NULL,
	[SINGLE_BUTT_ROOT_GAP] [float] NULL,
	[DOUBLE_BUTT_OVERLAP] [float] NULL,
	[FILLET_BUTT_STEEL_DENSITY] [float] NULL,
	[WIDTH] [float] NULL,
	[OUTER_UNIT] [float] NULL,
	[FILLET_BUTT_SHEET_THICKNESS] [float] NULL,
	[SINGLE_BUTT_SEAM_LENGTH] [float] NULL,
	[BUTT_PENETRATION] [float] NULL,
	[SINGLE_BUTT_CAP] [float] NULL,
	[BUTT_SEAM_LENGTH] [float] NULL,
	[SINGLE_BUTT_PENETRATION] [float] NULL,
	[THICKNESS] [float] NULL,
	[BUTT_OVERLAP] [float] NULL,
	[HEIGHT] [float] NULL,
	[DOUBLE_BUTT_SEAM_LENGTH] [float] NULL,
	[WIDTH_UNIT] [float] NULL,
	[INNER_DIAMETER] [float] NULL,
	[DOUBLE_BUTT_SHEET_THICKNESS] [float] NULL,
	[SINGLE_BUTT_STEEL_DENSITY] [float] NULL,
	[SIZE_UNIT] [float] NULL,
	[FILLET_BUTT_SEAM_LENGTH] [float] NULL,
	[OUTER_DIAMETER] [float] NULL,
	[SINGLE_BUTT_DEPTH_OF_ROOT_FACE] [float] NULL,
	[WELDING_JSON] [nvarchar](max) NULL,
 CONSTRAINT [PK_SPECTS_SPECT_VAR_ID] PRIMARY KEY CLUSTERED 
(
	[SPECT_VAR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [SPECTS] ADD  CONSTRAINT [DF_SPECTS_IS_MIX_PRODUCT]  DEFAULT ((0)) FOR [IS_MIX_PRODUCT]
GO



GO

/****** Object:  Table [SPECTS_ROW]    Script Date: 3/25/2026 10:19:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SPECTS_ROW](
	[SPECT_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[SPECT_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[AMOUNT_VALUE] [float] NULL,
	[TOTAL_VALUE] [float] NULL,
	[MONEY_CURRENCY] [nvarchar](43) NULL,
	[PROPERTY_ID] [int] NULL,
	[VARIATION_ID] [int] NULL,
	[TOTAL_MIN] [float] NULL,
	[TOTAL_MAX] [float] NULL,
	[PRODUCT_NAME] [nvarchar](500) NULL,
	[IS_PROPERTY] [int] NULL,
	[IS_CONFIGURE] [bit] NULL,
	[DIFF_PRICE] [float] NULL,
	[PRODUCT_COST] [float] NULL,
	[PRODUCT_COST_MONEY] [nvarchar](43) NULL,
	[PRODUCT_COST_ID] [int] NULL,
	[IS_SEVK] [bit] NULL,
	[TOLERANCE] [int] NULL,
	[RELATED_SPECT_ID] [int] NULL,
	[SHELF_NUMBER] [nvarchar](43) NULL,
	[PRODUCT_MANUFACT_CODE] [nvarchar](100) NULL,
	[PRODUCT_SPACE] [float] NULL,
	[PRODUCT_DISPLAY] [float] NULL,
	[PRODUCT_RATE] [float] NULL,
	[PRODUCT_LIST_PRICE] [float] NULL,
	[LINE_NUMBER] [int] NULL,
	[CONFIGURATOR_VARIATION_ID] [int] NULL,
	[DIMENSION] [float] NULL,
	[RELATED_TREE_ID] [int] NULL,
	[OPERATION_TYPE_ID] [int] NULL,
	[IS_QUALITY_TYPE] [bit] NULL,
	[QUALITY_TYPE_ID] [int] NULL,
	[QUALITY_STANDART_VALUE] [float] NULL,
	[QUALITY_MEASURE] [float] NULL,
	[QUALITY_TOLERANCE] [float] NULL,
	[FIRE_AMOUNT] [float] NULL,
	[PRODUCT_HEIGHT] [float] NULL,
	[PRODUCT_THICKNESS] [float] NULL,
	[TREE_TYPE] [int] NULL,
	[PRODUCT_SIZE] [float] NULL,
	[PRODUCT_WIDTH] [float] NULL,
 CONSTRAINT [PK_SPECTS_ROW_SPECT_ROW_ID] PRIMARY KEY CLUSTERED 
(
	[SPECT_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [SPECTS_ROW] ADD  DEFAULT ((0)) FOR [IS_SEVK]
GO



GO

/****** Object:  Table [OPERATION_TYPES]    Script Date: 3/25/2026 10:19:45 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [OPERATION_TYPES](
	[OPERATION_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[OPERATION_TYPE] [nvarchar](250) NULL,
	[O_HOUR] [int] NULL,
	[O_MINUTE] [int] NULL,
	[COMMENT] [nvarchar](100) NULL,
	[COMMENT2] [nvarchar](100) NULL,
	[FILE_NAME] [nvarchar](max) NULL,
	[OPERATION_COST] [float] NULL,
	[MONEY] [nvarchar](50) NULL,
	[FILE_SERVER_ID] [int] NULL,
	[OPERATION_CODE] [nvarchar](50) NULL,
	[OPERATION_STATUS] [bit] NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_EMP] [int] NULL,
	[EZGI_H_SURE] [float] NULL,
	[IS_VIRTUAL] [bit] NULL,
	[EZGI_FORMUL] [nvarchar](250) NULL,
	[STOCK_ID] [int] NULL,
	[PRODUCT_NAME] [nvarchar](150) NULL,
 CONSTRAINT [PK_OPERATION_TYPES_OPERATION_TYPE_ID] PRIMARY KEY CLUSTERED 
(
	[OPERATION_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


GO

/****** Object:  Table [WORKSTATIONS]    Script Date: 3/25/2026 10:23:29 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [WORKSTATIONS](
	[STATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[IS_CAPACITY] [bit] NULL,
	[PROJECT_ID] [int] NULL,
	[UP_STATION] [int] NULL,
	[STATION_NAME] [nvarchar](100) NULL,
	[BRANCH] [int] NULL,
	[DEPARTMENT] [int] NULL,
	[PRODUCT] [int] NULL,
	[CAPACITY] [int] NULL,
	[VALUE_STATION] [float] NULL,
	[ENERGY] [int] NULL,
	[EMP_ID] [nvarchar](500) NULL,
	[OUTSOURCE_PARTNER] [int] NULL,
	[COMMENT] [nvarchar](250) NULL,
	[DOWN_STATIONS] [int] NULL,
	[ACTIVE] [bit] NULL,
	[COST] [float] NULL,
	[COST_MONEY] [nvarchar](43) NULL,
	[EMPLOYEE_NUMBER] [int] NULL,
	[SET_PERIOD_HOUR] [int] NULL,
	[SET_PERIOD_MINUTE] [int] NULL,
	[AVG_CAPACITY_DAY] [int] NULL,
	[AVG_CAPACITY_HOUR] [int] NULL,
	[ASSET_ID] [int] NULL,
	[BASIC_INPUT_ID] [int] NULL,
	[AVG_COST] [float] NULL,
	[EXIT_DEP_ID] [int] NULL,
	[EXIT_LOC_ID] [int] NULL,
	[ENTER_DEP_ID] [int] NULL,
	[ENTER_LOC_ID] [int] NULL,
	[PRODUCTION_DEP_ID] [int] NULL,
	[PRODUCTION_LOC_ID] [int] NULL,
	[WIDTH] [float] NULL,
	[LENGTH] [float] NULL,
	[HEIGHT] [float] NULL,
	[ELECTRIC_TYPE] [int] NULL,
	[DESIGN_INFO] [nvarchar](max) NULL,
	[MARINA_PART_TYPE_ID] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[REFLECTION_TYPE] [int] NULL,
	[UNIT2] [nvarchar](43) NULL,
	[EZGI_SETUP_TIME] [float] NULL,
 CONSTRAINT [PK_WORKSTATIONS_STATION_ID] PRIMARY KEY CLUSTERED 
(
	[STATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


GO

/****** Object:  Table [WORKSTATIONS_PRODUCTS]    Script Date: 3/25/2026 10:23:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [WORKSTATIONS_PRODUCTS](
	[WS_P_ID] [int] IDENTITY(1,1) NOT NULL,
	[WS_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[CAPACITY] [float] NULL,
	[PRODUCTION_TIME] [float] NULL,
	[PRODUCTION_TIME_TYPE] [float] NULL,
	[SETUP_TIME] [float] NULL,
	[MIN_PRODUCT_AMOUNT] [float] NULL,
	[PRODUCTION_TYPE] [bit] NULL,
	[PROCESS] [nvarchar](250) NULL,
	[MAIN_STOCK_ID] [int] NULL,
	[OPERATION_TYPE_ID] [int] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[RECORD_DATE] [datetime] NULL,
	[ASSET_ID] [int] NULL,
 CONSTRAINT [PK_WORKSTATIONS_PRODUCTS_WS_P_ID] PRIMARY KEY CLUSTERED 
(
	[WS_P_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO




GO

/****** Object:  Table [PRODUCTION_OPERATION]    Script Date: 3/25/2026 10:26:47 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_OPERATION](
	[P_OPERATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[P_ORDER_ID] [int] NULL,
	[AMOUNT] [float] NULL,
	[STATION_ID] [int] NULL,
	[OPERATION_TYPE_ID] [int] NULL,
	[STAGE] [int] NULL,
	[O_MINUTE] [float] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[RELATED_OP_ID] [int] NULL,
	[O_SETUP_TIME] [float] NULL,
	[O_EXTRA_PROCESS_TIME] [float] NULL,
	[O_CURRENT_NUMBER] [int] NULL,
	[O_TOTAL_PROCESS_TIME] [float] NULL,
	[O_START_DATE] [datetime] NULL,
	[O_FINISH_DATE] [datetime] NULL,
	[O_STATION_IP] [int] NULL,
 CONSTRAINT [PK_PRODUCTION_OPERATION_P_OPERATION_ID] PRIMARY KEY CLUSTERED 
(
	[P_OPERATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


GO

/****** Object:  Table [PRODUCTION_OPERATION_RESULT]    Script Date: 3/25/2026 10:27:07 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_OPERATION_RESULT](
	[OPERATION_RESULT_ID] [int] IDENTITY(1,1) NOT NULL,
	[P_ORDER_ID] [int] NULL,
	[OPERATION_ID] [int] NULL,
	[STATION_ID] [int] NULL,
	[REAL_AMOUNT] [float] NULL,
	[LOSS_AMOUNT] [float] NULL,
	[REAL_TIME] [float] NULL,
	[WAIT_TIME] [float] NULL,
	[ACTION_EMPLOYEE_ID] [int] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[OPERATION_GRUP_END_ID] [nchar](10) NULL,
	[ACTION_START_DATE] [datetime] NULL,
	[OPERATION_GRUP_ID] [int] NULL,
 CONSTRAINT [PK_PRODUCTION_OPERATION_RESULT_OPERATION_RESULT_ID] PRIMARY KEY CLUSTERED 
(
	[OPERATION_RESULT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



GO

/****** Object:  Table [PRODUCTION_OPERATION_RESULT_MAIN]    Script Date: 3/25/2026 10:27:59 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_OPERATION_RESULT_MAIN](
	[MAIN_RESULT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PARTY_ID] [int] NULL,
	[OPERATION_ID] [int] NULL,
	[STATION_ID] [int] NULL,
	[REAL_AMOUNT] [float] NULL,
	[LOSS_AMOUNT] [float] NULL,
	[REAL_TIME] [float] NULL,
	[WAIT_TIME] [float] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[ACTION_EMPLOYEE_ID] [int] NULL,
 CONSTRAINT [PK_PRODUCTION_OPERATION_RESULT_MAIN] PRIMARY KEY CLUSTERED 
(
	[MAIN_RESULT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



GO

/****** Object:  Table [PRODUCTION_ORDER_OPERATIONS]    Script Date: 3/25/2026 10:28:13 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_ORDER_OPERATIONS](
	[POR_OPERATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[P_ORDER_ID] [int] NULL,
	[TYPE] [int] NULL,
	[PAUSE_TYPE] [int] NULL,
	[OPERATION_DATE] [datetime] NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[EMPLOYEE_ID] [int] NULL,
	[ASSET_ID] [int] NULL,
	[SERIAL_NO] [nvarchar](50) NULL,
	[AMOUNT] [float] NULL,
	[PR_ORDER_ID] [int] NULL,
	[WRK_ROW_ID] [nvarchar](100) NULL,
	[START_COUNTER] [float] NULL,
	[FINISH_COUNTER] [float] NULL,
 CONSTRAINT [PK_PRODUCTION_ORDER_OPERATIONS_POR_OPERATION_ID] PRIMARY KEY CLUSTERED 
(
	[POR_OPERATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



GO

/****** Object:  Table [PRODUCTION_ORDER_OPERATIONS_EMPLOYEE]    Script Date: 3/25/2026 10:28:32 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_ORDER_OPERATIONS_EMPLOYEE](
	[OPERATIONS_EMPLOYEE_ID] [int] IDENTITY(1,1) NOT NULL,
	[OPERATION_ID] [int] NOT NULL,
	[EMPLOYEE_ID] [int] NOT NULL,
 CONSTRAINT [PK_PRODUCTION_ORDER_OPERATIONS_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[OPERATIONS_EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



GO

/****** Object:  Table [PRODUCTION_ORDER_OPERATIONS_PRODUCT]    Script Date: 3/25/2026 10:28:44 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_ORDER_OPERATIONS_PRODUCT](
	[POR_P_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[WRK_ROW_ID] [nvarchar](100) NULL,
	[P_ORDER_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[PRODUCT_NAME] [nvarchar](250) NULL,
	[AMOUNT] [float] NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
 CONSTRAINT [PK_PRODUCTION_ORDER_OPERATIONS_PRODUCT_POR_P_ROW_ID] PRIMARY KEY CLUSTERED 
(
	[POR_P_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



GO

/****** Object:  Table [PRODUCTION_ORDER_RESULTS]    Script Date: 3/25/2026 10:31:24 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_ORDER_RESULTS](
	[PR_ORDER_ID] [int] IDENTITY(1,1) NOT NULL,
	[P_ORDER_ID] [int] NULL,
	[STATION_ID] [int] NULL,
	[START_DATE] [datetime] NULL,
	[FINISH_DATE] [datetime] NULL,
	[LOT_NO] [nvarchar](100) NULL,
	[PR_RESULT_NO] [int] NULL,
	[PROCESS_ID] [int] NULL,
	[RESULT_NO] [nvarchar](43) NULL,
	[RESULT_NUMBER] [int] NULL,
	[ORDER_NO] [nvarchar](250) NULL,
	[REFERENCE_NO] [nvarchar](500) NULL,
	[POSITION_ID] [int] NULL,
	[PROD_ORD_RESULT_STAGE] [int] NULL,
	[EXIT_DEP_ID] [int] NULL,
	[EXIT_LOC_ID] [int] NULL,
	[ENTER_DEP_ID] [int] NULL,
	[ENTER_LOC_ID] [int] NULL,
	[PRODUCTION_DEP_ID] [int] NULL,
	[PRODUCTION_LOC_ID] [int] NULL,
	[PRODUCTION_ORDER_NO] [nvarchar](43) NULL,
	[STATION_ROUTE_COST] [float] NULL,
	[IS_STOCK_FIS] [bit] NULL,
	[LABOR_COST_SYSTEM] [float] NULL,
	[WRK_ROW_ID] [nvarchar](40) NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[EXPIRATION_DATE] [datetime] NULL,
	[PARTY_ID] [int] NULL,
	[CONSUMER_ID] [int] NULL,
	[COMPANY_ID] [int] NULL,
 CONSTRAINT [PK_PRODUCTION_ORDER_RESULTS_PR_ORDER_ID] PRIMARY KEY CLUSTERED 
(
	[PR_ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



GO

/****** Object:  Table [PRODUCTION_ORDER_RESULTS_MAIN]    Script Date: 3/25/2026 10:31:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_ORDER_RESULTS_MAIN](
	[PARTY_RESULT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PARTY_RESULT_NO] [nvarchar](50) NULL,
	[PARTY_ID] [int] NULL,
	[PARTY_NO] [nvarchar](50) NULL
) ON [PRIMARY]
GO


GO

/****** Object:  Table [PRODUCTION_ORDER_RESULTS_ROW]    Script Date: 3/25/2026 10:31:45 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_ORDER_RESULTS_ROW](
	[PR_ORDER_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[TYPE] [int] NULL,
	[PR_ORDER_ID] [int] NULL,
	[BARCODE] [nvarchar](43) NULL,
	[NAME_PRODUCT] [nvarchar](500) NULL,
	[STOCK_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[AMOUNT] [float] NULL,
	[KDV_PRICE] [float] NULL,
	[UNIT_NAME] [nvarchar](65) NULL,
	[UNIT_ID] [int] NULL,
	[SPECT_ID] [int] NULL,
	[SPECT_NAME] [nvarchar](500) NULL,
	[SERIAL_NO] [nvarchar](50) NULL,
	[IS_SEVKIYAT] [bit] NULL,
	[COST_ID] [int] NULL,
	[PURCHASE_EXTRA_COST] [float] NULL,
	[PURCHASE_NET_SYSTEM] [float] NULL,
	[PURCHASE_NET_SYSTEM_MONEY] [nvarchar](43) NULL,
	[PURCHASE_EXTRA_COST_SYSTEM] [float] NULL,
	[PURCHASE_NET_SYSTEM_TOTAL] [float] NULL,
	[PURCHASE_NET] [float] NULL,
	[PURCHASE_NET_MONEY] [nvarchar](43) NULL,
	[PURCHASE_NET_TOTAL] [float] NULL,
	[UNIT2] [nvarchar](50) NULL,
	[AMOUNT2] [float] NULL,
	[SPEC_MAIN_ID] [int] NULL,
	[STATION_REFLECTION_COST_SYSTEM] [float] NULL,
	[TREE_TYPE] [nvarchar](43) NULL,
	[PRODUCT_NAME2] [nvarchar](500) NULL,
	[IS_STOCK_FIS] [bit] NULL,
	[IS_FROM_SPECT] [bit] NULL,
	[LABOR_COST_SYSTEM] [float] NULL,
	[FIRE_AMOUNT] [float] NULL,
	[PURCHASE_NET_2] [float] NULL,
	[PURCHASE_NET_MONEY_2] [nvarchar](43) NULL,
	[IS_FREE_AMOUNT] [bit] NULL,
	[LOT_NO] [nvarchar](100) NULL,
	[PURCHASE_EXTRA_COST_SYSTEM_2] [float] NULL,
	[WRK_ROW_ID] [nvarchar](50) NULL,
	[WRK_ROW_RELATION_ID] [nvarchar](50) NULL,
	[LINE_NUMBER] [int] NULL,
	[IS_MANUAL_COST] [bit] NULL,
	[EXPIRATION_DATE] [datetime] NULL,
	[P_ORDER_ID] [int] NULL,
	[WIDTH] [float] NULL,
	[HEIGHT] [float] NULL,
	[LENGTH] [float] NULL,
	[WEIGHT] [float] NULL,
	[SPECIFIC_WEIGHT] [float] NULL,
	[WORK_ID] [int] NULL,
	[WORK_HEAD] [nvarchar](50) NULL,
 CONSTRAINT [PK_PRODUCTION_ORDER_RESULTS_ROW_PR_ORDER_ROW_ID] PRIMARY KEY CLUSTERED 
(
	[PR_ORDER_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [PRODUCTION_ORDER_RESULTS_ROW] ADD  DEFAULT (N'S') FOR [TREE_TYPE]
GO

ALTER TABLE [PRODUCTION_ORDER_RESULTS_ROW] ADD  DEFAULT ((0)) FOR [IS_FROM_SPECT]
GO



GO

/****** Object:  Table [PRODUCTION_ORDERS]    Script Date: 3/25/2026 10:31:56 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_ORDERS](
	[P_ORDER_ID] [int] IDENTITY(1,1) NOT NULL,
	[STOCK_ID] [int] NULL,
	[DP_ORDER_ID] [int] NULL,
	[ORDER_ID] [int] NULL,
	[STATION_ID] [int] NULL,
	[START_DATE] [datetime] NULL,
	[FINISH_DATE] [datetime] NULL,
	[QUANTITY] [float] NULL,
	[STATUS_ID] [int] NULL,
	[STATUS] [int] NULL,
	[PROJECT_ID] [int] NULL,
	[P_ORDER_NO] [nvarchar](50) NULL,
	[PO_RELATED_ID] [int] NULL,
	[ORDER_ROW_ID] [int] NULL,
	[SPECT_VAR_ID] [int] NULL,
	[SPECT_VAR_NAME] [nvarchar](500) NULL,
	[DETAIL] [nvarchar](2000) NULL,
	[PROD_ORDER_STAGE] [int] NULL,
	[IS_STOCK_RESERVED] [bit] NULL,
	[PRINT_COUNT] [int] NULL,
	[IS_DEMONTAJ] [bit] NULL,
	[LOT_NO] [nvarchar](100) NULL,
	[REFERENCE_NO] [nvarchar](50) NULL,
	[PRODUCTION_LEVEL] [nvarchar](50) NULL,
	[SPEC_MAIN_ID] [int] NULL,
	[PRODUCT_NAME2] [nvarchar](500) NULL,
	[IS_GROUP_LOT] [bit] NULL,
	[IS_STAGE] [int] NULL,
	[WRK_ROW_ID] [nvarchar](40) NULL,
	[EXIT_DEP_ID] [int] NULL,
	[EXIT_LOC_ID] [int] NULL,
	[DEMAND_NO] [nvarchar](50) NULL,
	[PRODUCTION_DEP_ID] [int] NULL,
	[PRODUCTION_LOC_ID] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[WORK_ID] [int] NULL,
	[RESULT_AMOUNT] [float] NULL,
	[WRK_ROW_RELATION_ID] [nvarchar](50) NULL,
	[GROUP_LOT_NO] [nvarchar](50) NULL,
	[PARTY_ID] [int] NULL,
	[PARTNER_WORK_STAGE] [int] NULL,
	[IS_COLLECTED] [bit] NULL,
	[IS_URGENT] [bit] NULL,
	[QUANTITY_2] [int] NULL,
	[UNIT_2] [nvarchar](50) NULL,
	[IS_CONTROL_EMP] [int] NULL,
	[IS_CONTROL_DATE] [datetime] NULL,
	[FINISH_DATE_REAL] [datetime] NULL,
	[START_DATE_REAL] [datetime] NULL,
	[START_EMP_ID] [int] NULL,
	[FINISH_EMP_ID] [int] NULL,
 CONSTRAINT [PK_PRODUCTION_ORDERS] PRIMARY KEY CLUSTERED 
(
	[P_ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [PRODUCTION_ORDERS] ADD  DEFAULT ((0)) FOR [IS_URGENT]
GO


GO

/****** Object:  Table [PRODUCTION_ORDERS]    Script Date: 3/25/2026 10:31:56 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_ORDERS](
	[P_ORDER_ID] [int] IDENTITY(1,1) NOT NULL,
	[STOCK_ID] [int] NULL,
	[DP_ORDER_ID] [int] NULL,
	[ORDER_ID] [int] NULL,
	[STATION_ID] [int] NULL,
	[START_DATE] [datetime] NULL,
	[FINISH_DATE] [datetime] NULL,
	[QUANTITY] [float] NULL,
	[STATUS_ID] [int] NULL,
	[STATUS] [int] NULL,
	[PROJECT_ID] [int] NULL,
	[P_ORDER_NO] [nvarchar](50) NULL,
	[PO_RELATED_ID] [int] NULL,
	[ORDER_ROW_ID] [int] NULL,
	[SPECT_VAR_ID] [int] NULL,
	[SPECT_VAR_NAME] [nvarchar](500) NULL,
	[DETAIL] [nvarchar](2000) NULL,
	[PROD_ORDER_STAGE] [int] NULL,
	[IS_STOCK_RESERVED] [bit] NULL,
	[PRINT_COUNT] [int] NULL,
	[IS_DEMONTAJ] [bit] NULL,
	[LOT_NO] [nvarchar](100) NULL,
	[REFERENCE_NO] [nvarchar](50) NULL,
	[PRODUCTION_LEVEL] [nvarchar](50) NULL,
	[SPEC_MAIN_ID] [int] NULL,
	[PRODUCT_NAME2] [nvarchar](500) NULL,
	[IS_GROUP_LOT] [bit] NULL,
	[IS_STAGE] [int] NULL,
	[WRK_ROW_ID] [nvarchar](40) NULL,
	[EXIT_DEP_ID] [int] NULL,
	[EXIT_LOC_ID] [int] NULL,
	[DEMAND_NO] [nvarchar](50) NULL,
	[PRODUCTION_DEP_ID] [int] NULL,
	[PRODUCTION_LOC_ID] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[WORK_ID] [int] NULL,
	[RESULT_AMOUNT] [float] NULL,
	[WRK_ROW_RELATION_ID] [nvarchar](50) NULL,
	[GROUP_LOT_NO] [nvarchar](50) NULL,
	[PARTY_ID] [int] NULL,
	[PARTNER_WORK_STAGE] [int] NULL,
	[IS_COLLECTED] [bit] NULL,
	[IS_URGENT] [bit] NULL,
	[QUANTITY_2] [int] NULL,
	[UNIT_2] [nvarchar](50) NULL,
	[IS_CONTROL_EMP] [int] NULL,
	[IS_CONTROL_DATE] [datetime] NULL,
	[FINISH_DATE_REAL] [datetime] NULL,
	[START_DATE_REAL] [datetime] NULL,
	[START_EMP_ID] [int] NULL,
	[FINISH_EMP_ID] [int] NULL,
 CONSTRAINT [PK_PRODUCTION_ORDERS] PRIMARY KEY CLUSTERED 
(
	[P_ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [PRODUCTION_ORDERS] ADD  DEFAULT ((0)) FOR [IS_URGENT]
GO


GO

/****** Object:  Table [PRODUCTION_ORDERS_ROW]    Script Date: 3/25/2026 10:32:16 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_ORDERS_ROW](
	[PRODUCTION_ORDER_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCTION_ORDER_ID] [int] NULL,
	[ORDER_ROW_ID] [int] NULL,
	[ORDER_ID] [int] NULL,
	[TYPE] [int] NULL,
	[PLAN_ID] [int] NULL,
	[OP_ID] [int] NULL,
	[P_ORDER_ID] [int] NULL,
 CONSTRAINT [PK_PRODUCTION_ORDERS_ROW_PRODUCTION_ORDER_ROW_ID] PRIMARY KEY CLUSTERED 
(
	[PRODUCTION_ORDER_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


GO

/****** Object:  Table [PRODUCTION_ORDERS_STOCKS]    Script Date: 3/25/2026 10:32:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_ORDERS_STOCKS](
	[POR_STOCK_ID] [int] IDENTITY(1,1) NOT NULL,
	[P_ORDER_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[SPECT_MAIN_ID] [int] NULL,
	[AMOUNT] [float] NULL,
	[TYPE] [int] NULL,
	[PRODUCT_UNIT_ID] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[IS_PHANTOM] [bit] NULL,
	[IS_SEVK] [bit] NULL,
	[IS_PROPERTY] [int] NULL,
	[IS_FREE_AMOUNT] [bit] NULL,
	[FIRE_AMOUNT] [float] NULL,
	[FIRE_RATE] [float] NULL,
	[SPECT_MAIN_ROW_ID] [int] NULL,
	[IS_FLAG] [bit] NULL,
	[WRK_ROW_ID] [nvarchar](50) NULL,
	[LINE_NUMBER] [int] NULL,
	[LOT_NO] [nvarchar](100) NULL,
	[SPECT_VAR_ID] [int] NULL,
	[PRTOTM_DETAIL] [nvarchar](150) NULL,
	[AMOUNT2] [float] NULL,
 CONSTRAINT [PK_PRODUCTION_ORDERS_STOCKS] PRIMARY KEY CLUSTERED 
(
	[POR_STOCK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [PRODUCTION_ORDERS_STOCKS] ADD  DEFAULT ((0)) FOR [IS_PHANTOM]
GO

ALTER TABLE [PRODUCTION_ORDERS_STOCKS] ADD  DEFAULT ((0)) FOR [IS_SEVK]
GO

ALTER TABLE [PRODUCTION_ORDERS_STOCKS] ADD  DEFAULT ((0)) FOR [IS_FREE_AMOUNT]
GO



GO

/****** Object:  Table [PRODUCTION_PLAN_PARTER]    Script Date: 3/25/2026 10:32:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PRODUCTION_PLAN_PARTER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[WORK_START_DATE] [datetime] NULL,
	[WORK_END_DATE] [datetime] NULL,
	[P_ORDER_ID] [int] NULL,
	[STATION_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



GO

/****** Object:  Table [SPECT_MAIN]    Script Date: 3/25/2026 10:33:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SPECT_MAIN](
	[SPECT_MAIN_ID] [int] IDENTITY(1,1) NOT NULL,
	[WRK_ID] [nvarchar](100) NULL,
	[SPECT_MAIN_NAME] [nvarchar](500) NULL,
	[SPECT_TYPE] [int] NULL,
	[DETAIL] [nvarchar](max) NULL,
	[PRODUCT_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[IS_TREE] [bit] NULL,
	[SPECT_STATUS] [bit] NULL,
	[FUSEACTION] [nvarchar](150) NULL,
	[IS_LIMITED_STOCK] [bit] NULL,
	[SPECIAL_CODE_1] [nvarchar](250) NULL,
	[SPECIAL_CODE_2] [nvarchar](250) NULL,
	[SPECIAL_CODE_3] [nvarchar](250) NULL,
	[SPECIAL_CODE_4] [nvarchar](250) NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_PAR] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[RECORD_DATE] [datetime] NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_PAR] [int] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[RECORD_CON] [int] NULL,
	[UPDATE_CON] [int] NULL,
	[IS_MIX_PRODUCT] [bit] NULL,
	[STAGE] [int] NULL,
	[EMPLOYEE_ID] [int] NULL,
	[SAVE_DATE] [datetime] NULL,
 CONSTRAINT [PK_SPECT_MAIN_SPECT_MAIN_ID] PRIMARY KEY CLUSTERED 
(
	[SPECT_MAIN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [SPECT_MAIN] ADD  DEFAULT ((1)) FOR [SPECT_STATUS]
GO

ALTER TABLE [SPECT_MAIN] ADD  DEFAULT ((1)) FOR [IS_LIMITED_STOCK]
GO

ALTER TABLE [SPECT_MAIN] ADD  CONSTRAINT [DF_SPECT_MAIN_IS_MIX_PRODUCT]  DEFAULT ((0)) FOR [IS_MIX_PRODUCT]
GO




GO

/****** Object:  Table [SPECT_MAIN_ROW]    Script Date: 3/25/2026 10:33:49 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SPECT_MAIN_ROW](
	[SPECT_MAIN_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[SPECT_MAIN_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[AMOUNT] [float] NULL,
	[PROPERTY_ID] [int] NULL,
	[VARIATION_ID] [int] NULL,
	[TOTAL_MIN] [float] NULL,
	[TOTAL_MAX] [float] NULL,
	[PRODUCT_NAME] [nvarchar](500) NULL,
	[IS_PROPERTY] [int] NULL,
	[IS_CONFIGURE] [bit] NULL,
	[IS_SEVK] [bit] NULL,
	[TOTAL_VALUE] [float] NULL,
	[TOLERANCE] [int] NULL,
	[PRODUCT_SPACE] [float] NULL,
	[PRODUCT_DISPLAY] [float] NULL,
	[PRODUCT_RATE] [float] NULL,
	[PRODUCT_LIST_PRICE] [float] NULL,
	[CALCULATE_TYPE] [int] NULL,
	[RELATED_MAIN_SPECT_ID] [int] NULL,
	[RELATED_MAIN_SPECT_NAME] [nvarchar](150) NULL,
	[LINE_NUMBER] [int] NULL,
	[DIMENSION] [float] NULL,
	[CONFIGURATOR_VARIATION_ID] [int] NULL,
	[IS_PHANTOM] [bit] NULL,
	[RELATED_TREE_ID] [int] NULL,
	[OPERATION_TYPE_ID] [int] NULL,
	[QUESTION_ID] [int] NULL,
	[STATION_ID] [int] NULL,
	[IS_FREE_AMOUNT] [bit] NULL,
	[FIRE_AMOUNT] [float] NULL,
	[FIRE_RATE] [float] NULL,
	[DETAIL] [nvarchar](150) NULL,
	[IS_QUALITY_TYPE] [bit] NULL,
	[QUALITY_TYPE_ID] [int] NULL,
	[QUALITY_STANDART_VALUE] [float] NULL,
	[QUALITY_MEASURE] [float] NULL,
	[QUALITY_TOLERANCE] [float] NULL,
 CONSTRAINT [PK_SPECT_MAIN_ROW_SPECT_MAIN_ROW_ID] PRIMARY KEY CLUSTERED 
(
	[SPECT_MAIN_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [SPECT_MAIN_ROW] ADD  DEFAULT ((0)) FOR [IS_PHANTOM]
GO



GO

/****** Object:  Table [SPECTS]    Script Date: 3/25/2026 10:34:08 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SPECTS](
	[SPECT_VAR_ID] [int] IDENTITY(1,1) NOT NULL,
	[WRK_ID] [nvarchar](100) NULL,
	[PRODUCT_CONFIGURATOR_ID] [int] NULL,
	[SPECT_VAR_NAME] [nvarchar](500) NULL,
	[SPECT_TYPE] [int] NULL,
	[DETAIL] [nvarchar](max) NULL,
	[PRODUCT_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[TOTAL_AMOUNT] [float] NULL,
	[OTHER_MONEY_CURRENCY] [nvarchar](43) NULL,
	[OTHER_TOTAL_AMOUNT] [float] NULL,
	[IS_TREE] [bit] NULL,
	[PRODUCT_AMOUNT] [float] NULL,
	[PRODUCT_AMOUNT_CURRENCY] [nvarchar](43) NULL,
	[SPECT_COST] [float] NULL,
	[SPECT_COST_CURRENCY] [nvarchar](43) NULL,
	[SPECT_MAIN_ID] [int] NULL,
	[FILE_NAME] [nvarchar](50) NULL,
	[FILE_SERVER_ID] [int] NULL,
	[MARJ_TOTAL_AMOUNT] [float] NULL,
	[MARJ_OTHER_TOTAL_AMOUNT] [float] NULL,
	[MARJ_AMOUNT] [float] NULL,
	[MARJ_PERCENT] [float] NULL,
	[IS_LIMITED_STOCK] [bit] NULL,
	[SPECIAL_CODE_1] [nvarchar](250) NULL,
	[SPECIAL_CODE_2] [nvarchar](250) NULL,
	[SPECIAL_CODE_3] [nvarchar](250) NULL,
	[SPECIAL_CODE_4] [nvarchar](250) NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_CONS] [int] NULL,
	[RECORD_PAR] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[RECORD_DATE] [datetime] NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_PAR] [int] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_CONS] [int] NULL,
	[IS_MIX_PRODUCT] [bit] NULL,
	[STAGE] [int] NULL,
	[EMPLOYEE_ID] [int] NULL,
	[SAVE_DATE] [datetime] NULL,
	[DOUBLE_BUTT_ROOT_GAP] [float] NULL,
	[DOUBLE_BUTT_SEAM_GROOVE] [float] NULL,
	[DOUBLE_BUTT_DEPTH_OF_ROOT_FACE] [float] NULL,
	[DOUBLE_BUTT_CAP] [float] NULL,
	[BUTT_ROOT_GAP] [float] NULL,
	[BUTT_STEEL_DENSITY] [float] NULL,
	[SINGLE_BUTT_ALPHA1] [float] NULL,
	[SINGLE_BUTT_ALPHA2] [float] NULL,
	[FILLET_BUTT_CAP] [float] NULL,
	[WELDING_ID] [int] NULL,
	[SINGLE_BUTT_OVERLAP] [float] NULL,
	[BUTT_CAP] [float] NULL,
	[SIZE] [float] NULL,
	[DOUBLE_BUTT_ALPHA_1] [float] NULL,
	[DOUBLE_BUTT_ALPHA_2] [float] NULL,
	[DOUBLE_BUTT_STEEL_DENSITY] [float] NULL,
	[QUALITY_ID] [int] NULL,
	[DOUBLE_BUTT_ALPHA_3] [float] NULL,
	[DOUBLE_BUTT_ALPHA_4] [float] NULL,
	[DIAMETER] [float] NULL,
	[DOUBLE_BUTT_CAP_2] [float] NULL,
	[PRODUCT_CAT] [int] NULL,
	[CAP_UNIT] [float] NULL,
	[BUTT_SHEET_THICKNESS] [float] NULL,
	[SINGLE_BUTT_SHEET_THICKNESS] [float] NULL,
	[SINGLE_BUTT_ROOT_GAP] [float] NULL,
	[DOUBLE_BUTT_OVERLAP] [float] NULL,
	[FILLET_BUTT_STEEL_DENSITY] [float] NULL,
	[WIDTH] [float] NULL,
	[OUTER_UNIT] [float] NULL,
	[FILLET_BUTT_SHEET_THICKNESS] [float] NULL,
	[SINGLE_BUTT_SEAM_LENGTH] [float] NULL,
	[BUTT_PENETRATION] [float] NULL,
	[SINGLE_BUTT_CAP] [float] NULL,
	[BUTT_SEAM_LENGTH] [float] NULL,
	[SINGLE_BUTT_PENETRATION] [float] NULL,
	[THICKNESS] [float] NULL,
	[BUTT_OVERLAP] [float] NULL,
	[HEIGHT] [float] NULL,
	[DOUBLE_BUTT_SEAM_LENGTH] [float] NULL,
	[WIDTH_UNIT] [float] NULL,
	[INNER_DIAMETER] [float] NULL,
	[DOUBLE_BUTT_SHEET_THICKNESS] [float] NULL,
	[SINGLE_BUTT_STEEL_DENSITY] [float] NULL,
	[SIZE_UNIT] [float] NULL,
	[FILLET_BUTT_SEAM_LENGTH] [float] NULL,
	[OUTER_DIAMETER] [float] NULL,
	[SINGLE_BUTT_DEPTH_OF_ROOT_FACE] [float] NULL,
	[WELDING_JSON] [nvarchar](max) NULL,
 CONSTRAINT [PK_SPECTS_SPECT_VAR_ID] PRIMARY KEY CLUSTERED 
(
	[SPECT_VAR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [SPECTS] ADD  CONSTRAINT [DF_SPECTS_IS_MIX_PRODUCT]  DEFAULT ((0)) FOR [IS_MIX_PRODUCT]
GO



GO

/****** Object:  Table [SPECTS_ROW]    Script Date: 3/25/2026 10:34:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SPECTS_ROW](
	[SPECT_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[SPECT_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[AMOUNT_VALUE] [float] NULL,
	[TOTAL_VALUE] [float] NULL,
	[MONEY_CURRENCY] [nvarchar](43) NULL,
	[PROPERTY_ID] [int] NULL,
	[VARIATION_ID] [int] NULL,
	[TOTAL_MIN] [float] NULL,
	[TOTAL_MAX] [float] NULL,
	[PRODUCT_NAME] [nvarchar](500) NULL,
	[IS_PROPERTY] [int] NULL,
	[IS_CONFIGURE] [bit] NULL,
	[DIFF_PRICE] [float] NULL,
	[PRODUCT_COST] [float] NULL,
	[PRODUCT_COST_MONEY] [nvarchar](43) NULL,
	[PRODUCT_COST_ID] [int] NULL,
	[IS_SEVK] [bit] NULL,
	[TOLERANCE] [int] NULL,
	[RELATED_SPECT_ID] [int] NULL,
	[SHELF_NUMBER] [nvarchar](43) NULL,
	[PRODUCT_MANUFACT_CODE] [nvarchar](100) NULL,
	[PRODUCT_SPACE] [float] NULL,
	[PRODUCT_DISPLAY] [float] NULL,
	[PRODUCT_RATE] [float] NULL,
	[PRODUCT_LIST_PRICE] [float] NULL,
	[LINE_NUMBER] [int] NULL,
	[CONFIGURATOR_VARIATION_ID] [int] NULL,
	[DIMENSION] [float] NULL,
	[RELATED_TREE_ID] [int] NULL,
	[OPERATION_TYPE_ID] [int] NULL,
	[IS_QUALITY_TYPE] [bit] NULL,
	[QUALITY_TYPE_ID] [int] NULL,
	[QUALITY_STANDART_VALUE] [float] NULL,
	[QUALITY_MEASURE] [float] NULL,
	[QUALITY_TOLERANCE] [float] NULL,
	[FIRE_AMOUNT] [float] NULL,
	[PRODUCT_HEIGHT] [float] NULL,
	[PRODUCT_THICKNESS] [float] NULL,
	[TREE_TYPE] [int] NULL,
	[PRODUCT_SIZE] [float] NULL,
	[PRODUCT_WIDTH] [float] NULL,
 CONSTRAINT [PK_SPECTS_ROW_SPECT_ROW_ID] PRIMARY KEY CLUSTERED 
(
	[SPECT_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [SPECTS_ROW] ADD  DEFAULT ((0)) FOR [IS_SEVK]
GO

