-- PostgreSQL migration for REPORTS table

CREATE TABLE IF NOT EXISTS reports (
	report_id integer GENERATED BY DEFAULT AS IDENTITY,
	report_name varchar(250),
	report_detail varchar(500),
	template_id integer,
	is_special boolean DEFAULT false,
	cfm_file_name varchar(250),
	cfm_file_server_id integer,
	file_name varchar(250),
	file_server_id integer,
	record_date timestamp DEFAULT now(),
	record_ip varchar(50),
	record_emp integer,
	update_date timestamp,
	update_ip varchar(50),
	update_emp integer,
	report_status boolean DEFAULT false,
	admin_status boolean,
	is_file boolean,
	main_process_cat_id integer,
	report_cat_id integer,
	structure text,
	is_dashboard integer,
	modul_no integer,
	CONSTRAINT pk_reports_report_id PRIMARY KEY (report_id)
);