-- Superseded by docker/update-db/36_create_ship_roll_tables.sql.
-- The original version of this migration created a separate ship_rolls table,
-- which conflicted conceptually with the finalized ship_roll_plan / ship_roll
-- model used by the application screens. Keep this migration as a no-op so
-- sequential update runners do not create an unused parallel table.
