-- Machine fault numbers are generated by the application as
-- ARZ-YYYYMMDD-<sequence value>. The sequence guarantees uniqueness
-- without relying on random values.
CREATE SEQUENCE IF NOT EXISTS machine_fault_no_seq START WITH 1 INCREMENT BY 1;
